name: OpenStreetMap
targets:
  OpenStreetMap:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [OpenStreetMap]
    info:
      path: ./Info.plist
      version: 0.6
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
